name: smart_prefs
description: A flexible, type-safe preference management system supporting local, remote, and volatile storage with an elegant enum-based API.
version: 0.1.2
homepage: https://github.com/tomasdrz/smart_prefs
repository: https://github.com/tomasdrz/smart_prefs

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0

dev_dependencies:
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
